# pacificeast.com — /contact-us-privacy/. Formidable Forms (Opt-Out only —
# "PacificEast does not maintain or store consumer information", no
# Access/Delete offered). Fields have stable-per-form-instance but
# auto-generated ids (field_gnxso etc.) — targeted by `name`
# (item_meta[N]) instead, which is more legible. A trailing text field
# (item_meta[129]) has Formidable's own `frm_verify` class — its
# documented built-in honeypot — deliberately left BLANK.
#
# CAUTION: "Submission Confirmation" is a required checkbox reading "I
# confirm that this submission is not being generated by a third-party
# automated service" — an explicit anti-automation attestation, not a
# CAPTCHA. Checking it would be a false statement, so — same as
# altairdata.com's "manual submission only" attestation elsewhere in this
# repo — this scraper fills every other field but deliberately leaves this
# checkbox unchecked and stops there, regardless of DRY_RUN; a human must
# review, check it themselves, solve the Cloudflare Turnstile, and submit.
# "Identity & Authorization Confirmation" (a normal identity attestation,
# not an automation claim) is checked normally.
import asyncio

from src.dsar.super_scraper import SuperScraper

from pydoll.browser.chromium import Chrome
from pydoll.browser.options import ChromiumOptions

URL = "https://www.pacificeast.com/contact-us-privacy/"


async def main():
    options = ChromiumOptions()
    super_scraper = SuperScraper()
    options.binary_location = super_scraper.CHROMIUM_LOCATION
    options.add_argument("--no-sandbox")

    async with Chrome(options=options) as browser:
        tab = await browser.start()
        await tab.go_to(URL)
        await asyncio.sleep(5)

        fields = {
            "item_meta[95]": SuperScraper.FIRST_NAME,
            "item_meta[96]": SuperScraper.LAST_NAME,
            "item_meta[97]": SuperScraper.PHONE_NUMBER,
            "item_meta[98]": SuperScraper.EMAIL,
            "item_meta[99][line1]": SuperScraper.ADDRESS,
            "item_meta[99][line2]": SuperScraper.ADDRESS_LINE_TWO,
            "item_meta[99][city]": SuperScraper.CITY,
            "item_meta[99][state]": SuperScraper.STATE,
            "item_meta[99][zip]": SuperScraper.ZIP_CODE,
        }
        for field_name, value in fields.items():
            if not value:
                continue
            field = await tab.find(xpath=f"//input[@name='{field_name}']", raise_exc=False)
            if field:
                await field.type_text(value)
            else:
                print(f"{super_scraper.OOPS} field '{field_name}' not found")

        identity_checkbox = await tab.find(xpath="//input[@name='item_meta[126][]']", raise_exc=False)
        if identity_checkbox:
            await identity_checkbox.click()
        else:
            print(f"{super_scraper.OOPS} Identity & Authorization Confirmation checkbox not found")

        await asyncio.sleep(1)
        await SuperScraper.screenshot(tab, "resources/screenshots/pacificeast_dry_run.png")
        print(
            "\nForm filled but NOT submitted. The 'Submission Confirmation' checkbox "
            "attests the request is NOT from an automated service, which would be false "
            "here — left unchecked deliberately, regardless of DRY_RUN. A Cloudflare "
            "Turnstile challenge is also present. A human must check that box, solve "
            "the Turnstile, and click Submit themselves."
        )


asyncio.run(main())
